[정수론] 9월 3일
Altu-Bitu-7/Altu-Bitu-KimMinJi pull request #3
Opened 2024-09-03 07:24 UTC by Janice0381

### 인적사항
이름: 김민지
학번: 2277039

### 과제 제출
기존 제출: 1735, 2840, 6588
추가 제출:

2024-09-06 11:50 UTC, kimeunsom approved these changes

2024-09-06 11:50 UTC, kimeunsom commented on BOJ_2840.cpp
> +    return 0;
인덱스가 음수가 되지 않도록 잘 처리되어 동작하고 있네요 ~ :)

2024-09-06 11:50 UTC, kimeunsom commented on BOJ_2840.cpp
구현 문제의 복잡한 예외 상황들을 잘 처리해주셨네요 ~ 샘플 코드 참고하셔서, main 함수를 간소화하고 필요한 로직들은 구조화된 함수로 정리하여 재사용성이 높은 코드를 짜는 연습을 해보시는 것도 추천드립니다 :) 고생하셨습니다 !

2024-09-07 09:03 UTC, avocado8 commented on BOJ_6588.cpp
p1 / 민지님 안녕하세요 :3 코드 작성 후 백준 채점하기에 돌려보셨을까요? 정답 처리가 되지 않고 있어 출석처리가 어렵습니다 ㅜ . ㅜ 확인하시고, 리뷰 참고하여 함께 고쳐보아요! 질문은 언제나 환영합니다~

2024-09-07 09:04 UTC, avocado8 commented on BOJ_6588.cpp
> +void getPrimes() {
소수 찾기 알고리즘 좋아요~

2024-09-07 09:07 UTC, avocado8 commented on BOJ_6588.cpp
> +		}
반복문을 사용해 해당 숫자를 두 숫자의 합으로 분리한 뒤, 각각 소수인지 확인하는 방법을 사용하셨네요! 좋은 방법입니다 :3 그치만 이렇게 검사한다면, 반복을 돌던 중 두 숫자 모두 소수가 아닐 때는 "Goldbach's conjecture is wrong" 이 매번 출력되게 되겠죠? (문제의 테스트케이스에서도 확인할 수 있으실 거예요) 그렇다면 매 반복마다 else문을 사용해주지 말고, 반복문으로 모든 검사를 끝낸 이후에도 올바른 소수 두개를 찾지 못했다면 wrong메시지를 출력하면 되지 않을까요? 한번 수정해봅시다!

2024-09-07 09:08 UTC, avocado8 commented on BOJ_6588.cpp
> +const int MAX = 1000000;
상수 선언 굿!

2024-09-07 09:09 UTC, avocado8 requested changes
6588(p1)
민지님 안녕하세요 :3 코드 작성 후 백준 채점하기에 돌려보셨을까요? 정답 처리가 되지 않고 있어 출석처리가 어렵습니다 ㅜ . ㅜ 확인하시고, 리뷰 참고하여 함께 고쳐보아요! 질문은 언제나 환영합니다~

2024-09-08 04:55 UTC, Janice0381 commented
> 6588(p1) 민지님 안녕하세요 :3 코드 작성 후 백준 채점하기에 돌려보셨을까요? 정답 처리가 되지 않고 있어 출석처리가 어렵습니다 ㅜ . ㅜ 확인하시고, 리뷰 참고하여 함께 고쳐보아요! 질문은 언제나 환영합니다~

2024-09-08 05:01 UTC, avocado8 commented
민지님 안녕하세요! 달아주신 코멘트 상으로 코드 확인이 어려워서, 로컬에서 파일을 수정하신 뒤 커밋을 다시 해주시고 리뷰어를 호출해주실 수 있을까요? 어렵다면 슬랙 메시지로 보내주셔도 좋습니다!

2024-09-08 11:40 UTC, avocado8 approved these changes
6588번 p1리뷰 수정 확인했습니다 :3

2024-09-09 12:01 UTC, merged

2024-09-10 01:17 UTC, ruruisryu reviewed
1735번 너무 잘 풀어주셨습니다! 분수의 합을 구하는 과정을 조금 더 개선해볼 수 있을 것 같아 코멘트 남겨드렸으니 확인 후 고민해보시면 좋을 것 같아요! 나머지는 너무 좋습니다. 수고하셨어요!! ☺️

2024-09-10 01:17 UTC, ruruisryu commented on 정수론/BOJ_1735.cpp
> +	int sum = product1 + product2;
1735번은 분수의 합을 구한 결과를 기약분수로 나타내주기 위해 분모와 분자의 최대공약수를 구해 나눠주는 문제입니다. 통분할 떄의 과정을 생각해보면 분수의 합을 구해주는 부분을 좀 더 간단하게 짜볼 수 있을 것 같아요! 충분히 고민해보신 후 답안으로 올라온 자료를 확인해보시면 좋을 것 같습니다~☺️