[브루트포스] 9월 10일
Altu-Bitu-7/Altu-Bitu-KimMinJi pull request #6
Opened 2024-09-10 09:28 UTC by Janice0381

### 인적 사항
이름: 김민지
학번: 2277039

### 과제 제출
기존 제출: 1063, 1436, 11723
추가 제출:

2024-09-14 03:07 UTC, avocado8 requested changes
11723(p1)
민지님 안녕하세요 :3 11723번 리뷰 남겨드렸으니 확인하시고 코드 수정하신 뒤 리뷰어를 다시 호출해주세요!
과제에서 어려움이 있을 경우 슬랙 메시지를 남겨주시면 바로 도움 드리도록 하겠습니다 ☺️

2024-09-14 03:07 UTC, avocado8 commented on 브루트포스/BOJ_11723.cpp
> +        cin >> input.first >> input.second;
p1. 현재 pair로 입력을 받고 있는데, 주어진 연산 중에서 x를 사용하지 않는(즉 n만 필요로 하는) 연산이 있어요. 이 경우에는 second를 입력받지 않기 때문에 cin이 정상적으로 종료되지 않아 원하는 실행 결과가 나오지 않고 있네요 :( 
pair로 입력받기보다는, x를 사용하지 않는 연산일 경우에는 n만 입력받고, x를 사용하는 연산일 경우에는 x를 추가로 입력받는 식으로 다시 구현해보신 뒤 결과를 확인해주세요!

2024-09-16 04:41 UTC, Janice0381 commented on 브루트포스/BOJ_11723.cpp
> +        cin >> input.first >> input.second;
11723번 수정해서 커밋 다시 했습니다. 확인 부탁드립니다!

2024-09-16 14:47 UTC, mons-trev approved these changes
안녕하세요 민지님!
4주차 1063 킹 문제 피드백 드려요😊
4주차도 열심히 참여해 주셔서 감사합니다👍
잘 안 풀린다면 리뷰어를 호출해주시거나 언제든 슬랙 질문으로 호출해주시길 바랍니다~!

2024-09-16 14:47 UTC, mons-trev commented on 브루트포스/BOJ_1063.cpp
> +void moveLocation(char direction, int move_x, int move_y) {
moveLocation 으로 바뀐 move_x 와 move_y 를 main 함수에서 사용하도록 로직을 작성하셨군요!!
여기서 바뀐 move_x ,  move_y 는 이 moveLocation 함수 내에서만 유효합니다😊
그렇기 때문에 이 함수에서 바뀐 move_x, move_y 값을 return 해서 main 에서 값을 받거나,
& 같이 레퍼런스를 매개변수로 받는 방법을 사용하시면 바뀐 move_x, move_y 가 main 함수 내에 반영 됩니다!

2024-09-16 14:47 UTC, mons-trev commented on 브루트포스/BOJ_1063.cpp
> +        if ((king_x + move_x <= MAX) && (king_y + move_y <= MAX)) {
'H', '8' 을 벗어나는 것 외에 '0' 과 'A' 를 벗어나는 경우도 같이 고려해야 해요!

2024-09-16 14:47 UTC, mons-trev commented on 브루트포스/BOJ_1063.cpp
> +                if ((stone_x + move_x <= MAX) && (stone_y + move_y <= MAX)) {
마찬가지로 'H', '8' 을 벗어나는 것 외에 '0' 과 'A' 를 벗어나는 경우도 같이 고려해야 해요!

2024-09-16 14:47 UTC, mons-trev commented on 브루트포스/BOJ_1063.cpp
> +            }
만약, 이동시킨 king 의 위치가 stone 과 같아서 stone 도 같은 방향으로 이동시켰는데 체스판 위를 벗어나는 경우도 고려해야 합니다~! 그렇게 된다면 king 의 이동도 무효화해야 될텐데 이 부분을 else 문을 이용해서 로직 짜보시길 바랍니다~!

2024-09-16 14:47 UTC, mons-trev commented on 브루트포스/BOJ_1063.cpp
> +    int stone_y = stone_location[1] - '0';
문자열->숫자, 숫자->문자열 변환이 헷갈릴 수 있는데 너무 잘 구현해주셨네요👍👍

2024-09-17 04:18 UTC, mons-trev commented
안녕하세요 민지님:)
수정해주신 두 코드 정답 확인하였습니다!
4주차도 너무 고생많으셨습니다😊👍

2024-09-17 04:35 UTC, merged